### ISSUE TITLE
Bad request?

### ISSUE THREAD

**Issue by edonkeycoin** [leszekrogowski/remote-sign-tool#4]
Thanks for this great tool! We're interested in using it so that we can share an EV certificate with multiple build systems.

We can get it to work great locally where both the client and server are on the same system and it's configured with localhost as its host name. But when we try to run the server on one system and the client on another, where we're using the raw IP address as the host, we always get a "BadRequest" error.

We're pretty sure we've worked through any firewall issues. And the log on the server side indicates that data is being received:

2019-02-08 11:04:50.4655 INFO Uploading zip file: ajeirbes.4it.zip, containing files: C:\playground\RemoteSignTool\signing\tosign.exe
2019-02-08 11:04:57.5587 INFO Sending: (0%) Transfered: 40, Total: 8036
2019-02-08 11:04:57.5587 INFO Sending: (1%) Transfered: 102, Total: 8036
2019-02-08 11:04:57.5587 INFO Sending: (52%) Transfered: 4198, Total: 8036
2019-02-08 11:04:57.5587 INFO Sending: (99%) Transfered: 7992, Total: 8036
2019-02-08 11:04:57.5587 INFO Sending: (100%) Transfered: 8036, Total: 8036
2019-02-08 11:04:57.5587 INFO Receive: (100%) Transfered: 334, Total: 334
2019-02-08 11:04:57.5744 ERROR Status code: BadRequest

Any thoughts on how we can work around this? Perhaps we need to add a DNS entry for a real domain name instead of the raw IP address?

Thanks in advance for your help.

**Comment by leszekrogowski** [comment]
Are you running a server with elevated permissions (Run as Administrator)? I believe it might be connected with permission issue.

**Comment by edonkeycoin** [comment]
Thanks for the quick response!

I think we're running the server under normal permissions. We can try running it as admin. 

We're also experimenting with giving it a real domain via DNS instead of a raw IP address. We'll finish that experiment before trying the admin permissions route.

**Comment by edonkeycoin** [comment]
Neither elevating permissions nor moving to a real domain has worked. Also, we're seeing different failures depending if we're running under VS debugging verses just running the apps themselves.

Should it be expected that the server app can run independently of any ASP or ISS configuration? Or is it that there's some system level config (other than the firewall) that needs to be in place in order to get the server to work?

**Comment by leszekrogowski** [comment]
Have you changed BaseAddress in Settings.settings (it should then regenerate App.Settings file)?

`<userSettings>

    <RemoteSignTool.Server.Properties.Settings>
      <setting name="BaseAddress" serializeAs="String">
        <value>http://localhost:9000</value> 
      </setting>
      <setting name="FolderToSignAtStartup" serializeAs="String">
        <value />
      </setting>
    </RemoteSignTool.Server.Properties.Settings>

  </userSettings>`

**Comment by edonkeycoin** [comment]
Thanks. Yes, we definitely did that. We've tried fixed IP addresses (instead of 'localhost') as well as a domain name available via DNS.

We're trying a clean experiment now on two new systems to see if perhaps some old cruft was getting in the way. Hopefully we can blast through this.

**Comment by edonkeycoin** [comment]
Just a quick note to say that we got this working. And yes, we think that you must run as an admin because apparently the port number of 9000 is within a certain range where that's needed.

I plan to write up what we did to get this to work in case it's interesting to anyone else.

**Comment by leszekrogowski** [comment]
Great to hear that and it would be great to document the resolution. When I've a little more time I'll create Wiki for the project.

**Comment by edonkeycoin** [comment]
Here's the steps that we found worked. Not as complicated as I thought, but we had some missteps along the way.

1. In the solution, search and replace "localhost" with the server IP address. We realize that some of the files are generated, but without a list of what we should not change we just did them all.

2. On the server create an "Inbound" firewall rule to permit port 9000 on server machine. No firewall changes are needed on the client.

3. Run server as "admin". We think this is necessary because of the port number. It might not be needed if the port number is higher, but we haven't explored this yet.

4. If using an EV certificate, the password to the secure token must be entered on the server side for a signing operation. We further used the security token utility software such that the password is only required once per login. 

The password must be provided while physically connected to the server. You cannot use a remote desktop session. Attempts to remote desktop into the server will cause a new login and the password will have to be provided again.

At some point we'll explore whether or not we can provide the password programmatically.

**Comment by edonkeycoin** [comment]
One more thing. We're seeing pretty bad performance for large binaries. For example, a 548 MB installer can take upwards of 5 hours to complete. Although it's very inconsistent. Sometimes we've seen it take a mere 15 minutes, but that is rare.

Looking at the breakdown of the time it's mostly the download of the signed binary from the server to the client. The upload from client to server only takes about a minute.

Both the client and server have gigabit Ethernet connections on the same gigabit switch. There's no router based throttling happening.

Any thoughts as to why this might be so slow? Perhaps there are client side changes (like increased buffering) that we could make to improve this?

**Comment by leszekrogowski** [comment]
Thanks for the description. As far as I know, it's not possible to pass password programatically for SafeNet Client, however, if you find anything please share your findings.

With regard to poor performance, can you please try to change buffer to 1MB or bigger for StreamContent in [FileResult.cs](https://github.com/leszekrogowski/remote-sign-tool/blob/master/RemoteSignTool/RemoteSignTool.Server/Results/FileResult.cs)?

I have found the following article at StackOverflow explaining how to do it: [https://stackoverflow.com/a/34913084](https://stackoverflow.com/a/34913084).

**Comment by edonkeycoin** [comment]
Thanks for the suggestion. Wow, that made a huge difference! 

We went with 10 MB and our round trip times are well under a minute for the same large binary.

Kind of hard to imagine why the default size would be 4k nowadays. But anyway, it was easy enough to make the change (once we knew to try it).

Do you think it makes sense to change the sources to do this automatically? You could pick a reasonable buffer size as a constant that people could change as it suits them.

Also, if we make any progress on the SafeNet Client password front, I'll report back. For now though we're probably going to live with the pain. We might pinch this off to a dedicated VM that we authorize once and then never update or touch again ;-)

**Comment by leszekrogowski** [comment]
It makes sense to make a change to buffer size. If you have already done it, maybe you can send PR and we can merge it.

**Comment by edonkeycoin** [comment]
I'll check with the guy that did the work and we'll figure out how to get it to you. I'm going out of town so it might be quiet from us for about a week.
